name: Build Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK

    runs-on: ubuntu-latest
    steps:
      - name: "Run test suite"
        uses: msfjarvis/setup-android@1.0
        with:
          entrypoint: ./gradlew
          args: dependencies spotlessApply detekt assembleDebug