name: Build Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK

    runs-on: ubuntu-latest
    steps:
      - name: "Build APK"
        uses: vgaidarji/android-github-actions/build@v1.0.0
        args: ./gradlew assembleDebug